services:
  app_24bet:
    build: 
      context: backend
      dockerfile: Dockerfile
    expose:
      - "8080"  # importante: no necesitas publicar el puerto
    networks:
      - my_custom_network
    environment:
      DB_URL: jdbc:postgresql://200.58.100.28:5432/db_lbf
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
      TZ: Etc/GMT+6
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app_lbf
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - VITE_API_BASE_URL=https://laburbujafeliz.com/lbf
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
