services:
  app_lbf:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://200.58.100.28:5432/db_lbf
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app_lbf
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - VITE_API_BASE_URL=http://vps-5038974-x.dattaweb.com:8080/lbf

networks:
  my_custom_network:
    driver: bridge